name: Build and Deploy to Local K8s

on:
  push:
    branches: [ main ]

env:
  IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/tech-challenge-app

jobs:
  build-deploy:
    runs-on: [self-hosted, Windows, X64]

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build jar
      run: .\gradlew.bat bootJar

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Set Docker image tag
      id: tag
      shell: powershell
      run: |
        $shortSha = "${{ github.sha }}".Substring(0, 7)
        echo "TAG=$shortSha" >> $env:GITHUB_ENV

    - name: Build Docker image
      run: docker build -t tech-challenge-app:$TAG .

    - name: Tag Docker image for Docker Hub
      run: docker tag tech-challenge-app:$TAG ${{ secrets.DOCKER_USERNAME }}/tech-challenge-app:$TAG

    - name: Push Docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/tech-challenge-app:$TAG
